name: Main

on:
- push
- pull_request

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@v5
      with:
        node-version: 20
        cache: yarn
    - name: Lint and test
      run: |
        yarn install --frozen-lockfile
        yarn lint
        yarn prettier --check '**/*'
        yarn test
